set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_SYSTEM_NAME WASM)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_CXX_COMPILER_TARGET wasm32-unknown-unknown)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_LINKER "wasm-ld")